In [1]:
%run main_analyzer.py

Open Source Data Quality Analyzer
Project started successfully!

In [2]:
%run main_analyzer.py

Open Source Data Quality Analyzer

Data Quality Report:
             Check  Result Status
     Total Records       3   INFO
    Missing Values       0   PASS
    Duplicate Rows       0   PASS
Invalid Quantities       0   PASS
    Invalid Prices       0   PASS

Report saved: day31_quality_report.csv

In [3]:
import os
import pandas as pd

file_name = "day31_quality_report.csv"

if os.path.exists(file_name):
    report = pd.read_csv(file_name)

    print("✅ Report created successfully!")
    print("File size:", os.path.getsize(file_name), "bytes")
    print("Total checks:", len(report))
    display(report)
else:
    print("❌ Report not found. Please run main_analyzer.py first.")

✅ Report created successfully!
File size: 139 bytes
Total checks: 5

                Check  Result Status
0       Total Records       3   INFO
1      Missing Values       0   PASS
2      Duplicate Rows       0   PASS
3  Invalid Quantities       0   PASS
4      Invalid Prices       0   PASS

In [4]:
%run main_analyzer.py

Open Source Data Quality Analyzer

Data Quality Report:
             Check  Result Status
     Total Records       4   INFO
    Missing Values       1   FAIL
    Duplicate Rows       0   PASS
Invalid Quantities       1   FAIL
    Invalid Prices       0   PASS

Report saved: day31_quality_report.csv

In [5]:
%run main_analyzer.py sample_sales_2.csv

Open Source Data Quality Analyzer
Input file: sample_sales_2.csv

Data Quality Report:
             Check  Result Status
     Total Records       4   INFO
    Missing Values       1   FAIL
    Duplicate Rows       0   PASS
Invalid Quantities       1   FAIL
    Invalid Prices       0   PASS

Report saved: day31_quality_report.csv

In [6]:
import os

print(os.path.exists("day31_quality_report.csv"))

True

In [7]:
import pandas as pd

report = pd.read_csv("day31_quality_report.csv")
display(report)

                Check  Result Status
0       Total Records       4   INFO
1      Missing Values       1   FAIL
2      Duplicate Rows       0   PASS
3  Invalid Quantities       1   FAIL
4      Invalid Prices       0   PASS

In [8]:
%run main_analyzer.py sales_cleaned_day3.csv

Open Source Data Quality Analyzer
Input file: sales_cleaned_day3.csv

Data Quality Report:
             Check  Result Status
     Total Records       5   INFO
    Missing Values       0   PASS
    Duplicate Rows       0   PASS
Invalid Quantities       0   PASS
    Invalid Prices       0   PASS

Report saved: day31_quality_report.csv

In [9]:
%run main_analyzer.py wrong_file.csv

Open Source Data Quality Analyzer
Input file: wrong_file.csv
Error: CSV file not found: wrong_file.csv

In [10]:
import os

files = [
    "main_analyzer.py",
    "day31_main_analyzer.ipynb",
    "day31_quality_report.csv"
]

for file in files:
    print(file, "->", "Available" if os.path.exists(file) else "Missing")

main_analyzer.py -> Available
day31_main_analyzer.ipynb -> Available
day31_quality_report.csv -> Available

In [11]:
import os

print(os.path.exists("README.md"))

True

In [12]:
!git --version

git version 2.48.1.windows.1

In [13]:
!git init

Initialized empty Git repository in C:/Users/asd/Desktop/open-source-data-quality-analyzer/.git/

In [14]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	README.md
	__pycache__/
	data_quality_analyzer.py
	day10_data_quality_report.csv
	day10_python_script.ipynb
	day11_combined_quality_report.csv
	day11_multiple_csv_analysis.ipynb
	day12_automatic_csv_detection.ipynb
	day12_automatic_quality_report.csv
	day13_quality_summary.csv
	day13_quality_summary.ipynb
	day14_quality_score.ipynb
	day14_quality_score_report.csv
	day15_quality_score_comparison.csv
	day15_quality_score_comparison.ipynb
	day16_quality_score_comparison.png
	day16_quality_score_visualization.ipynb
	day17_final_quality_report.csv
	day17_final_quality_report.ipynb
	day18_multi_dataset_analyzer.ipynb
	day18_multi_dataset_quality_report.csv
	day19_automatic_data_quality_analyzer.ipynb
	day19_automatic_quality_report.csv
	day1_data_inspection.ipynb
	day20_quality_status_chart.png
	day20_quality_summary_dashboard.ipynb
	day21_overall_quality_score.ipynb
	day21_overall_quality_score_report.csv
	day22_multi_dataset_score_comparison.csv
	day22_multi_dataset_score_comparison.ipynb
	day23_quality_comparison_chart.png
	day23_quality_comparison_dashboard.ipynb
	day23_quality_comparison_report.csv
	day24_detailed_quality_analysis.ipynb
	day24_detailed_quality_report.csv
	day25_automatic_issue_detection.ipynb
	day25_automatic_issue_report.csv
	day26_automatic_data_cleaning.ipynb
	day26_cleaned_sales.csv
	day26_cleaning_summary_report.csv
	day27_combined_quality_report.csv
	day27_reusable_data_quality_analyzer.ipynb
	day27_reusable_quality_report.csv
	day28_error_handling.ipynb
	day28_error_handling_report.csv
	day29_professional_data_quality_analyzer.ipynb
	day29_professional_quality_report.csv
	day2_missing_values_duplicates.ipynb
	day30_complete_data_quality_analyzer.ipynb
	day30_final_quality_report.csv
	day31_main_analyzer.ipynb
	day31_quality_report.csv
	day3_missing_values.ipynb
	day4_data_validation.ipynb
	day4_validation_report.csv
	day5_summary_statistics.ipynb
	day6_data_quality_report.csv
	day6_data_quality_report.ipynb
	day7_data_quality_analyzer.ipynb
	day7_data_quality_report.csv
	day8_combined_quality_report.csv
	day8_data_quality_analyzer.ipynb
	day9_data_quality_score.ipynb
	day9_quality_score_comparison.csv
	main_analyzer.py
	sales_cleaned_day3.csv
	sales_without_duplicates.csv
	sample_sales.csv
	sample_sales_2.csv

nothing added to commit but untracked files present (use "git add" to track)

In [15]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/README-checkpoint.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/data_quality_analyzer-checkpoint.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day10_python_script-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day11_multiple_csv_analysis-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day12_automatic_csv_detection-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day13_quality_summary-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day14_quality_score-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day15_quality_score_comparison-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day16_quality_score_visualization-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day17_final_quality_report-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day18_multi_dataset_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day19_automatic_data_quality_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day1_data_inspection-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day20_quality_summary_dashboard-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day21_overall_quality_score-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day22_multi_dataset_score_comparison-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day23_quality_comparison_dashboard-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day24_detailed_quality_analysis-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day25_automatic_issue_detection-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day26_automatic_data_cleaning-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day27_reusable_data_quality_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day28_error_handling-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day29_professional_data_quality_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day2_missing_values_duplicates-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day30_complete_data_quality_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day31_main_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day3_missing_values-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day4_data_validation-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day5_summary_statistics-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day6_data_quality_report-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day7_data_quality_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day8_data_quality_analyzer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/day9_data_quality_score-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/main_analyzer-checkpoint.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'data_quality_analyzer.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day10_python_script.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day11_multiple_csv_analysis.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day12_automatic_csv_detection.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day13_quality_summary.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day14_quality_score.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day15_quality_score_comparison.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day16_quality_score_visualization.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day17_final_quality_report.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day18_multi_dataset_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day19_automatic_data_quality_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day1_data_inspection.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day20_quality_summary_dashboard.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day21_overall_quality_score.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day22_multi_dataset_score_comparison.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day23_quality_comparison_dashboard.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day24_detailed_quality_analysis.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day25_automatic_issue_detection.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day26_automatic_data_cleaning.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day27_reusable_data_quality_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day28_error_handling.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day29_professional_data_quality_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day2_missing_values_duplicates.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day30_complete_data_quality_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day31_main_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day3_missing_values.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day4_data_validation.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day5_summary_statistics.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day6_data_quality_report.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day7_data_quality_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day8_data_quality_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'day9_data_quality_score.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'main_analyzer.py', LF will be replaced by CRLF the next time Git touches it

In [1]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .ipynb_checkpoints/README-checkpoint.md
	new file:   .ipynb_checkpoints/data_quality_analyzer-checkpoint.py
	new file:   .ipynb_checkpoints/day10_python_script-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day11_multiple_csv_analysis-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day12_automatic_csv_detection-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day13_quality_summary-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day14_quality_score-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day15_quality_score_comparison-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day16_quality_score_visualization-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day17_final_quality_report-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day18_multi_dataset_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day19_automatic_data_quality_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day1_data_inspection-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day20_quality_summary_dashboard-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day21_overall_quality_score-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day22_multi_dataset_score_comparison-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day23_quality_comparison_dashboard-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day24_detailed_quality_analysis-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day25_automatic_issue_detection-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day26_automatic_data_cleaning-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day27_reusable_data_quality_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day28_error_handling-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day29_professional_data_quality_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day2_missing_values_duplicates-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day30_complete_data_quality_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day31_main_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day3_missing_values-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day4_data_validation-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day5_summary_statistics-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day6_data_quality_report-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day7_data_quality_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day8_data_quality_analyzer-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day9_data_quality_score-checkpoint.ipynb
	new file:   .ipynb_checkpoints/day9_quality_score_comparison-checkpoint.csv
	new file:   .ipynb_checkpoints/main_analyzer-checkpoint.py
	new file:   .ipynb_checkpoints/sample_sales-checkpoint.csv
	new file:   README.md
	new file:   __pycache__/data_quality_analyzer.cpython-313.pyc
	new file:   data_quality_analyzer.py
	new file:   day10_data_quality_report.csv
	new file:   day10_python_script.ipynb
	new file:   day11_combined_quality_report.csv
	new file:   day11_multiple_csv_analysis.ipynb
	new file:   day12_automatic_csv_detection.ipynb
	new file:   day12_automatic_quality_report.csv
	new file:   day13_quality_summary.csv
	new file:   day13_quality_summary.ipynb
	new file:   day14_quality_score.ipynb
	new file:   day14_quality_score_report.csv
	new file:   day15_quality_score_comparison.csv
	new file:   day15_quality_score_comparison.ipynb
	new file:   day16_quality_score_comparison.png
	new file:   day16_quality_score_visualization.ipynb
	new file:   day17_final_quality_report.csv
	new file:   day17_final_quality_report.ipynb
	new file:   day18_multi_dataset_analyzer.ipynb
	new file:   day18_multi_dataset_quality_report.csv
	new file:   day19_automatic_data_quality_analyzer.ipynb
	new file:   day19_automatic_quality_report.csv
	new file:   day1_data_inspection.ipynb
	new file:   day20_quality_status_chart.png
	new file:   day20_quality_summary_dashboard.ipynb
	new file:   day21_overall_quality_score.ipynb
	new file:   day21_overall_quality_score_report.csv
	new file:   day22_multi_dataset_score_comparison.csv
	new file:   day22_multi_dataset_score_comparison.ipynb
	new file:   day23_quality_comparison_chart.png
	new file:   day23_quality_comparison_dashboard.ipynb
	new file:   day23_quality_comparison_report.csv
	new file:   day24_detailed_quality_analysis.ipynb
	new file:   day24_detailed_quality_report.csv
	new file:   day25_automatic_issue_detection.ipynb
	new file:   day25_automatic_issue_report.csv
	new file:   day26_automatic_data_cleaning.ipynb
	new file:   day26_cleaned_sales.csv
	new file:   day26_cleaning_summary_report.csv
	new file:   day27_combined_quality_report.csv
	new file:   day27_reusable_data_quality_analyzer.ipynb
	new file:   day27_reusable_quality_report.csv
	new file:   day28_error_handling.ipynb
	new file:   day28_error_handling_report.csv
	new file:   day29_professional_data_quality_analyzer.ipynb
	new file:   day29_professional_quality_report.csv
	new file:   day2_missing_values_duplicates.ipynb
	new file:   day30_complete_data_quality_analyzer.ipynb
	new file:   day30_final_quality_report.csv
	new file:   day31_main_analyzer.ipynb
	new file:   day31_quality_report.csv
	new file:   day3_missing_values.ipynb
	new file:   day4_data_validation.ipynb
	new file:   day4_validation_report.csv
	new file:   day5_summary_statistics.ipynb
	new file:   day6_data_quality_report.csv
	new file:   day6_data_quality_report.ipynb
	new file:   day7_data_quality_analyzer.ipynb
	new file:   day7_data_quality_report.csv
	new file:   day8_combined_quality_report.csv
	new file:   day8_data_quality_analyzer.ipynb
	new file:   day9_data_quality_score.ipynb
	new file:   day9_quality_score_comparison.csv
	new file:   main_analyzer.py
	new file:   sales_cleaned_day3.csv
	new file:   sales_without_duplicates.csv
	new file:   sample_sales.csv
	new file:   sample_sales_2.csv

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .ipynb_checkpoints/day31_main_analyzer-checkpoint.ipynb
	modified:   day31_main_analyzer.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

In [1]:
with open(".gitignore", "r") as file:
    print(file.read())

.ipynb_checkpoints/
__pycache__/
*.pyc

In [2]:
!git rm -r --cached .ipynb_checkpoints __pycache__

error: the following file has staged content different from both the
file and the HEAD:
    .ipynb_checkpoints/day31_main_analyzer-checkpoint.ipynb
(use -f to force removal)

In [3]:
!git rm -rf --cached .ipynb_checkpoints __pycache__

rm '.ipynb_checkpoints/README-checkpoint.md'
rm '.ipynb_checkpoints/data_quality_analyzer-checkpoint.py'
rm '.ipynb_checkpoints/day10_python_script-checkpoint.ipynb'
rm '.ipynb_checkpoints/day11_multiple_csv_analysis-checkpoint.ipynb'
rm '.ipynb_checkpoints/day12_automatic_csv_detection-checkpoint.ipynb'
rm '.ipynb_checkpoints/day13_quality_summary-checkpoint.ipynb'
rm '.ipynb_checkpoints/day14_quality_score-checkpoint.ipynb'
rm '.ipynb_checkpoints/day15_quality_score_comparison-checkpoint.ipynb'
rm '.ipynb_checkpoints/day16_quality_score_visualization-checkpoint.ipynb'
rm '.ipynb_checkpoints/day17_final_quality_report-checkpoint.ipynb'
rm '.ipynb_checkpoints/day18_multi_dataset_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day19_automatic_data_quality_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day1_data_inspection-checkpoint.ipynb'
rm '.ipynb_checkpoints/day20_quality_summary_dashboard-checkpoint.ipynb'
rm '.ipynb_checkpoints/day21_overall_quality_score-checkpoint.ipynb'
rm '.ipynb_checkpoints/day22_multi_dataset_score_comparison-checkpoint.ipynb'
rm '.ipynb_checkpoints/day23_quality_comparison_dashboard-checkpoint.ipynb'
rm '.ipynb_checkpoints/day24_detailed_quality_analysis-checkpoint.ipynb'
rm '.ipynb_checkpoints/day25_automatic_issue_detection-checkpoint.ipynb'
rm '.ipynb_checkpoints/day26_automatic_data_cleaning-checkpoint.ipynb'
rm '.ipynb_checkpoints/day27_reusable_data_quality_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day28_error_handling-checkpoint.ipynb'
rm '.ipynb_checkpoints/day29_professional_data_quality_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day2_missing_values_duplicates-checkpoint.ipynb'
rm '.ipynb_checkpoints/day30_complete_data_quality_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day31_main_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day3_missing_values-checkpoint.ipynb'
rm '.ipynb_checkpoints/day4_data_validation-checkpoint.ipynb'
rm '.ipynb_checkpoints/day5_summary_statistics-checkpoint.ipynb'
rm '.ipynb_checkpoints/day6_data_quality_report-checkpoint.ipynb'
rm '.ipynb_checkpoints/day7_data_quality_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day8_data_quality_analyzer-checkpoint.ipynb'
rm '.ipynb_checkpoints/day9_data_quality_score-checkpoint.ipynb'
rm '.ipynb_checkpoints/day9_quality_score_comparison-checkpoint.csv'
rm '.ipynb_checkpoints/main_analyzer-checkpoint.py'
rm '.ipynb_checkpoints/sample_sales-checkpoint.csv'
rm '__pycache__/data_quality_analyzer.cpython-313.pyc'

In [4]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   README.md
	new file:   data_quality_analyzer.py
	new file:   day10_data_quality_report.csv
	new file:   day10_python_script.ipynb
	new file:   day11_combined_quality_report.csv
	new file:   day11_multiple_csv_analysis.ipynb
	new file:   day12_automatic_csv_detection.ipynb
	new file:   day12_automatic_quality_report.csv
	new file:   day13_quality_summary.csv
	new file:   day13_quality_summary.ipynb
	new file:   day14_quality_score.ipynb
	new file:   day14_quality_score_report.csv
	new file:   day15_quality_score_comparison.csv
	new file:   day15_quality_score_comparison.ipynb
	new file:   day16_quality_score_comparison.png
	new file:   day16_quality_score_visualization.ipynb
	new file:   day17_final_quality_report.csv
	new file:   day17_final_quality_report.ipynb
	new file:   day18_multi_dataset_analyzer.ipynb
	new file:   day18_multi_dataset_quality_report.csv
	new file:   day19_automatic_data_quality_analyzer.ipynb
	new file:   day19_automatic_quality_report.csv
	new file:   day1_data_inspection.ipynb
	new file:   day20_quality_status_chart.png
	new file:   day20_quality_summary_dashboard.ipynb
	new file:   day21_overall_quality_score.ipynb
	new file:   day21_overall_quality_score_report.csv
	new file:   day22_multi_dataset_score_comparison.csv
	new file:   day22_multi_dataset_score_comparison.ipynb
	new file:   day23_quality_comparison_chart.png
	new file:   day23_quality_comparison_dashboard.ipynb
	new file:   day23_quality_comparison_report.csv
	new file:   day24_detailed_quality_analysis.ipynb
	new file:   day24_detailed_quality_report.csv
	new file:   day25_automatic_issue_detection.ipynb
	new file:   day25_automatic_issue_report.csv
	new file:   day26_automatic_data_cleaning.ipynb
	new file:   day26_cleaned_sales.csv
	new file:   day26_cleaning_summary_report.csv
	new file:   day27_combined_quality_report.csv
	new file:   day27_reusable_data_quality_analyzer.ipynb
	new file:   day27_reusable_quality_report.csv
	new file:   day28_error_handling.ipynb
	new file:   day28_error_handling_report.csv
	new file:   day29_professional_data_quality_analyzer.ipynb
	new file:   day29_professional_quality_report.csv
	new file:   day2_missing_values_duplicates.ipynb
	new file:   day30_complete_data_quality_analyzer.ipynb
	new file:   day30_final_quality_report.csv
	new file:   day31_main_analyzer.ipynb
	new file:   day31_quality_report.csv
	new file:   day3_missing_values.ipynb
	new file:   day4_data_validation.ipynb
	new file:   day4_validation_report.csv
	new file:   day5_summary_statistics.ipynb
	new file:   day6_data_quality_report.csv
	new file:   day6_data_quality_report.ipynb
	new file:   day7_data_quality_analyzer.ipynb
	new file:   day7_data_quality_report.csv
	new file:   day8_combined_quality_report.csv
	new file:   day8_data_quality_analyzer.ipynb
	new file:   day9_data_quality_score.ipynb
	new file:   day9_quality_score_comparison.csv
	new file:   main_analyzer.py
	new file:   sales_cleaned_day3.csv
	new file:   sales_without_duplicates.csv
	new file:   sample_sales.csv
	new file:   sample_sales_2.csv

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   day31_main_analyzer.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

In [5]:
!git add .gitignore day31_main_analyzer.ipynb

warning: in the working copy of 'day31_main_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it

In [1]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .gitignore
	new file:   README.md
	new file:   data_quality_analyzer.py
	new file:   day10_data_quality_report.csv
	new file:   day10_python_script.ipynb
	new file:   day11_combined_quality_report.csv
	new file:   day11_multiple_csv_analysis.ipynb
	new file:   day12_automatic_csv_detection.ipynb
	new file:   day12_automatic_quality_report.csv
	new file:   day13_quality_summary.csv
	new file:   day13_quality_summary.ipynb
	new file:   day14_quality_score.ipynb
	new file:   day14_quality_score_report.csv
	new file:   day15_quality_score_comparison.csv
	new file:   day15_quality_score_comparison.ipynb
	new file:   day16_quality_score_comparison.png
	new file:   day16_quality_score_visualization.ipynb
	new file:   day17_final_quality_report.csv
	new file:   day17_final_quality_report.ipynb
	new file:   day18_multi_dataset_analyzer.ipynb
	new file:   day18_multi_dataset_quality_report.csv
	new file:   day19_automatic_data_quality_analyzer.ipynb
	new file:   day19_automatic_quality_report.csv
	new file:   day1_data_inspection.ipynb
	new file:   day20_quality_status_chart.png
	new file:   day20_quality_summary_dashboard.ipynb
	new file:   day21_overall_quality_score.ipynb
	new file:   day21_overall_quality_score_report.csv
	new file:   day22_multi_dataset_score_comparison.csv
	new file:   day22_multi_dataset_score_comparison.ipynb
	new file:   day23_quality_comparison_chart.png
	new file:   day23_quality_comparison_dashboard.ipynb
	new file:   day23_quality_comparison_report.csv
	new file:   day24_detailed_quality_analysis.ipynb
	new file:   day24_detailed_quality_report.csv
	new file:   day25_automatic_issue_detection.ipynb
	new file:   day25_automatic_issue_report.csv
	new file:   day26_automatic_data_cleaning.ipynb
	new file:   day26_cleaned_sales.csv
	new file:   day26_cleaning_summary_report.csv
	new file:   day27_combined_quality_report.csv
	new file:   day27_reusable_data_quality_analyzer.ipynb
	new file:   day27_reusable_quality_report.csv
	new file:   day28_error_handling.ipynb
	new file:   day28_error_handling_report.csv
	new file:   day29_professional_data_quality_analyzer.ipynb
	new file:   day29_professional_quality_report.csv
	new file:   day2_missing_values_duplicates.ipynb
	new file:   day30_complete_data_quality_analyzer.ipynb
	new file:   day30_final_quality_report.csv
	new file:   day31_main_analyzer.ipynb
	new file:   day31_quality_report.csv
	new file:   day3_missing_values.ipynb
	new file:   day4_data_validation.ipynb
	new file:   day4_validation_report.csv
	new file:   day5_summary_statistics.ipynb
	new file:   day6_data_quality_report.csv
	new file:   day6_data_quality_report.ipynb
	new file:   day7_data_quality_analyzer.ipynb
	new file:   day7_data_quality_report.csv
	new file:   day8_combined_quality_report.csv
	new file:   day8_data_quality_analyzer.ipynb
	new file:   day9_data_quality_score.ipynb
	new file:   day9_quality_score_comparison.csv
	new file:   main_analyzer.py
	new file:   sales_cleaned_day3.csv
	new file:   sales_without_duplicates.csv
	new file:   sample_sales.csv
	new file:   sample_sales_2.csv

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   day31_main_analyzer.ipynb

In [2]:
!git commit -m "Add data quality analyzer project"

[master (root-commit) de70083] Add data quality analyzer project
 69 files changed, 12025 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 README.md
 create mode 100644 data_quality_analyzer.py
 create mode 100644 day10_data_quality_report.csv
 create mode 100644 day10_python_script.ipynb
 create mode 100644 day11_combined_quality_report.csv
 create mode 100644 day11_multiple_csv_analysis.ipynb
 create mode 100644 day12_automatic_csv_detection.ipynb
 create mode 100644 day12_automatic_quality_report.csv
 create mode 100644 day13_quality_summary.csv
 create mode 100644 day13_quality_summary.ipynb
 create mode 100644 day14_quality_score.ipynb
 create mode 100644 day14_quality_score_report.csv
 create mode 100644 day15_quality_score_comparison.csv
 create mode 100644 day15_quality_score_comparison.ipynb
 create mode 100644 day16_quality_score_comparison.png
 create mode 100644 day16_quality_score_visualization.ipynb
 create mode 100644 day17_final_quality_report.csv
 create mode 100644 day17_final_quality_report.ipynb
 create mode 100644 day18_multi_dataset_analyzer.ipynb
 create mode 100644 day18_multi_dataset_quality_report.csv
 create mode 100644 day19_automatic_data_quality_analyzer.ipynb
 create mode 100644 day19_automatic_quality_report.csv
 create mode 100644 day1_data_inspection.ipynb
 create mode 100644 day20_quality_status_chart.png
 create mode 100644 day20_quality_summary_dashboard.ipynb
 create mode 100644 day21_overall_quality_score.ipynb
 create mode 100644 day21_overall_quality_score_report.csv
 create mode 100644 day22_multi_dataset_score_comparison.csv
 create mode 100644 day22_multi_dataset_score_comparison.ipynb
 create mode 100644 day23_quality_comparison_chart.png
 create mode 100644 day23_quality_comparison_dashboard.ipynb
 create mode 100644 day23_quality_comparison_report.csv
 create mode 100644 day24_detailed_quality_analysis.ipynb
 create mode 100644 day24_detailed_quality_report.csv
 create mode 100644 day25_automatic_issue_detection.ipynb
 create mode 100644 day25_automatic_issue_report.csv
 create mode 100644 day26_automatic_data_cleaning.ipynb
 create mode 100644 day26_cleaned_sales.csv
 create mode 100644 day26_cleaning_summary_report.csv
 create mode 100644 day27_combined_quality_report.csv
 create mode 100644 day27_reusable_data_quality_analyzer.ipynb
 create mode 100644 day27_reusable_quality_report.csv
 create mode 100644 day28_error_handling.ipynb
 create mode 100644 day28_error_handling_report.csv
 create mode 100644 day29_professional_data_quality_analyzer.ipynb
 create mode 100644 day29_professional_quality_report.csv
 create mode 100644 day2_missing_values_duplicates.ipynb
 create mode 100644 day30_complete_data_quality_analyzer.ipynb
 create mode 100644 day30_final_quality_report.csv
 create mode 100644 day31_main_analyzer.ipynb
 create mode 100644 day31_quality_report.csv
 create mode 100644 day3_missing_values.ipynb
 create mode 100644 day4_data_validation.ipynb
 create mode 100644 day4_validation_report.csv
 create mode 100644 day5_summary_statistics.ipynb
 create mode 100644 day6_data_quality_report.csv
 create mode 100644 day6_data_quality_report.ipynb
 create mode 100644 day7_data_quality_analyzer.ipynb
 create mode 100644 day7_data_quality_report.csv
 create mode 100644 day8_combined_quality_report.csv
 create mode 100644 day8_data_quality_analyzer.ipynb
 create mode 100644 day9_data_quality_score.ipynb
 create mode 100644 day9_quality_score_comparison.csv
 create mode 100644 main_analyzer.py
 create mode 100644 sales_cleaned_day3.csv
 create mode 100644 sales_without_duplicates.csv
 create mode 100644 sample_sales.csv
 create mode 100644 sample_sales_2.csv

In [7]:
!git commit -m "Add data quality analyzer project"

[master 7e8b3b1] Add data quality analyzer project
 1 file changed, 150 insertions(+), 1 deletion(-)

In [12]:
!git status

On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   day31_main_analyzer.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [13]:
!git add day31_main_analyzer.ipynb

warning: in the working copy of 'day31_main_analyzer.ipynb', LF will be replaced by CRLF the next time Git touches it

In [14]:
!git commit -m "Update Day 31 analyzer notebook"

[master 7f985bc] Update Day 31 analyzer notebook
 1 file changed, 22 insertions(+), 22 deletions(-)

In [15]:
!git status

On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   day31_main_analyzer.ipynb

no changes added to commit (use "git add" and/or "git commit -a")